version: 2.1

references :
  - https://circleci.com/docs/2.0
   
jobs:
  build:
    executor:
    docker:
        - image: ghcr.io/cirruslabs/flutter:latest

    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test
      - run:
          name: Flutter Build
          command: flutter build apk
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
